[package]
name = "status_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"

[[bin]]
name = "open_fm"
path = "src/open_fm.rs"

[[bin]]
name = "status_bar"
path = "src/status_bar.rs"
